server:
   port: 8081
spring:
   application:
      name: microsevice-consumer-movie
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
   instance:
      prefer-ip-address: true