server:
   port: 8080
https:
  port: 443
  ssl:
    key-store: classpath:sample.jks
    key-store-password: secret
    key-password: password
spring:
   application:
      #注册到Eureka Server上的应用名称
      name: microservice-provider-user
   jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
         ddl-auto: none
   datasource:
      #platform: h2
      #driver-class-name: org.h2.Driver
      #url: jdbc:h2:file:~/test
      #username: sa
      #password: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      #schema: classpath:schema.sql
      #data: classpath:data.sql
eureka:
   client:
      serviceUrl:
         defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
   instance:
      #将自己的IP注册到Eureka Server
      prefer-ip-address: true
logging:
   level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.basicExtractor: TRACE